CREATE TABLE USUARIOS (
  idUSUARIOS INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  EMAIL VARCHAR(50)  NULL  ,
  E_PASSWORD VARCHAR(50)  NULL  ,
  NAME VARCHAR(100)  NULL  ,
  SURNAME VARCHAR(100)  NULL  ,
  PHONE INTEGER UNSIGNED  NULL    ,
PRIMARY KEY(idUSUARIOS));



CREATE TABLE SENSORES (
  idSENSORES INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  SENSOR_TYPE VARCHAR(100)  NOT NULL    ,
PRIMARY KEY(idSENSORES));



CREATE TABLE PARAMETRO_COLORES (
  idPARAMETRO_COLORES INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  VS_MIN VARCHAR(20)  NOT NULL  ,
  VS_MAX VARCHAR(20)  NOT NULL  ,
  VP_MIN VARCHAR(20)  NOT NULL  ,
  VP_MAX VARCHAR(20)  NOT NULL  ,
  ESTADO_PLANTA VARCHAR(30)  NOT NULL    ,
PRIMARY KEY(idPARAMETRO_COLORES));



CREATE TABLE ACTUADORES (
  idACTUADORES INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  ACTUATORS_TYPE VARCHAR(100)  NOT NULL    ,
PRIMARY KEY(idACTUADORES));



CREATE TABLE SENSOR_INFO (
  FECHA VARCHAR(100)  NOT NULL  ,
  SENSORES_idSENSORES INTEGER UNSIGNED  NOT NULL  ,
  DATO INTEGER UNSIGNED  NULL    ,
PRIMARY KEY(FECHA, SENSORES_idSENSORES)  ,
INDEX SENSOR_INFO_FKIndex1(SENSORES_idSENSORES),
  FOREIGN KEY(SENSORES_idSENSORES)
    REFERENCES SENSORES(idSENSORES)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE ACTUADOR_INFO (
  FECHA VARCHAR(100)  NOT NULL  ,
  ACTUADORES_idACTUADORES INTEGER UNSIGNED  NOT NULL  ,
  DATO BOOL  NULL    ,
PRIMARY KEY(FECHA, ACTUADORES_idACTUADORES)  ,
INDEX ACTUADOR_INFO_FKIndex1(ACTUADORES_idACTUADORES),
  FOREIGN KEY(ACTUADORES_idACTUADORES)
    REFERENCES ACTUADORES(idACTUADORES)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE PLANTAS (
  idSISTEMA INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  PARAMETRO_COLORES_idPARAMETRO_COLORES INTEGER UNSIGNED  NOT NULL  ,
  ACTUADORES_idACTUADORES INTEGER UNSIGNED  NOT NULL  ,
  SENSORES_idSENSORES INTEGER UNSIGNED  NOT NULL  ,
  NUM_PLANTAS INTEGER UNSIGNED  NOT NULL  ,
  PLANTS_TYPE VARCHAR(100)  NOT NULL    ,
PRIMARY KEY(idSISTEMA)  ,
INDEX SISTEMA_FKIndex1(SENSORES_idSENSORES)  ,
INDEX SISTEMA_FKIndex2(ACTUADORES_idACTUADORES)  ,
INDEX SISTEMA_FKIndex3(PARAMETRO_COLORES_idPARAMETRO_COLORES),
  FOREIGN KEY(SENSORES_idSENSORES)
    REFERENCES SENSORES(idSENSORES)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ACTUADORES_idACTUADORES)
    REFERENCES ACTUADORES(idACTUADORES)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PARAMETRO_COLORES_idPARAMETRO_COLORES)
    REFERENCES PARAMETRO_COLORES(idPARAMETRO_COLORES)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE PLANTAS_has_USUARIOS (
  PLANTAS_idSISTEMA INTEGER UNSIGNED  NOT NULL  ,
  USUARIOS_idUSUARIOS INTEGER UNSIGNED  NOT NULL    ,
PRIMARY KEY(PLANTAS_idSISTEMA, USUARIOS_idUSUARIOS)  ,
INDEX PLANTAS_has_USUARIOS_FKIndex1(PLANTAS_idSISTEMA)  ,
INDEX PLANTAS_has_USUARIOS_FKIndex2(USUARIOS_idUSUARIOS),
  FOREIGN KEY(PLANTAS_idSISTEMA)
    REFERENCES PLANTAS(idSISTEMA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(USUARIOS_idUSUARIOS)
    REFERENCES USUARIOS(idUSUARIOS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);




